name: Membership Verification

on:
  pull_request:
    paths:
      - "members/*.md"

jobs:
  verify-membership:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Membership Files
        run: |
          for file in members/*.md; do
            # Skip README.md from validation
            if [[ "$file" == "members/README.md" ]]; then
              continue
            fi

            # Check required fields
            if ! grep -q "Name: " "$file" || ! grep -q "Email: " "$file" || ! grep -q "GitHub Username: " "$file"; then
              echo "❌ Membership file $file is missing required fields."
              exit 1
            fi
          done

      - name: Membership Verification Complete
        run: echo "✅ All membership files are valid!"
